version: "3.8"

services:
  db:
    image: postgres
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=fhir_pg
    networks:
      - app

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - app
    command: bash -c "python app/manage.py"

networks:
  app:
    driver: bridge
